turtletide:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: manifest-stream-452700-g7
      dataset: turtletide_gold
      keyfile: /opt/airflow/turtletide-key.json
      location: US
      threads: 4
      job_execution_timeout_seconds: 300